apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::864897371056:role/eksctl-eksctl-demo-nodegroup-ng-0-NodeInstanceRole-1DDW0D10AO82U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::864897371056:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-08T03:36:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1741"
  uid: 1bd660a6-9a1b-4fcf-8cc4-fbc663b6e3a4
